import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByText('Sign in')).toBeVisible();
  await page.getByText('Sign in').click();
  await expect(page.getByText('Sign InAccess your saved')).toBeVisible();
  await expect(page.getByLabel('close modal')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Sign in with Basic BCeID' })).toBeVisible();
  await expect(page.locator('#modal-content')).toContainText('Sign In');
  await expect(page.locator('form')).toContainText('Access your saved cameras and routes');
  await expect(page.locator('form')).toContainText('Sign in with Basic BCeID');
  await expect(page.locator('form')).toContainText('Don\'t have a Basic BCeID Account?Click here to create one');
  await expect(page.getByRole('link', { name: 'Click here to create one' })).toBeVisible();
  await expect(page.locator('form')).toContainText('What is a BCeID?');
  await expect(page.getByLabel('What is a BCeID? BCeID is a')).toBeVisible();
  await page.getByRole('button', { name: 'Sign in with Basic BCeID' }).click();
  await page.locator('#user').click();
  await page.locator('#user').fill(`${process.env.BCEID_USER}`);
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill(`${process.env.BCEID_PASSWORD}`);
  await page.getByRole('button', { name: 'Continue' }).click();
  await expect(page.getByRole('button', { name: 'Favourites' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Account' })).toBeVisible();
  await page.getByRole('button', { name: 'Account' }).click();
  await expect(page.locator('#user-icon path')).toBeVisible();
  await expect(page.getByText(`${process.env.BCEID_EMAIL}`)).toBeVisible();
  await expect(page.getByText('Sign out')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Account settings' })).toBeVisible();
  await page.getByRole('link', { name: 'Account settings' }).click();
  await expect(page.locator('h1')).toContainText('My Account');
  await page.getByRole('button', { name: 'Favourites' }).click();
  await expect(page.getByRole('link', { name: 'My cameras' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'My routes' })).toBeVisible();
  await page.getByRole('link', { name: 'My cameras' }).click();
  await expect(page.locator('h1')).toContainText('My cameras');
  await expect(page.locator('#root')).toContainText('Manage and view your saved cameras here.');
  await page.getByRole('button', { name: 'Favourites' }).click();
  await page.getByRole('link', { name: 'My routes' }).click();
  await expect(page.locator('h1')).toContainText('My routes');
  await expect(page.locator('#root')).toContainText('Manage and view your saved routes here.');
  await page.getByRole('button', { name: 'Account' }).click();
  await page.getByText('Sign out').click();
  await expect(page.getByText('Sign OutSign out of DriveBC')).toBeVisible();
  await expect(page.getByLabel('close modal')).toBeVisible();
  await expect(page.locator('#modal-content')).toContainText('Sign Out');
  await expect(page.getByRole('button', { name: 'Sign out of DriveBC' })).toBeVisible();
  await page.getByRole('button', { name: 'Sign out of DriveBC' }).click();
  await expect(page.getByText('Sign InAccess your saved')).toBeVisible();
  await expect(page.getByLabel('close modal')).toBeVisible();
  await expect(page.locator('#modal-content')).toContainText('Sign In');
  await expect(page.locator('form')).toContainText('Access your saved cameras and routes');
  await expect(page.getByRole('button', { name: 'Sign in with Basic BCeID' })).toBeVisible();
  await expect(page.locator('form')).toContainText('Don\'t have a Basic BCeID Account?Click here to create one');
  await expect(page.locator('form')).toContainText('What is a BCeID?');
  await expect(page.getByLabel('What is a BCeID? BCeID is a')).toBeVisible();
});